Repository TradeableDigitalCard/TDC21, pull requests merged in 2021-09, with the labels that each got.

#15 TDC21-7 addedd blockchain.sh managing script
  blockchain.sh
  blockchain/Dockerfile
  docker-compose.yml
Labels: Foundational, subtask

#13 [TDC21-12] fix block explorer
  blockchain/BlockExplorerDockerfile
  docker-compose.yml
Labels: bug, Foundational, subtask

#11 [TDC21-6] Truffle project docker container
  TDC21/Dockerfile
  TDC21/src/build/contracts/Migrations.json
  TDC21/src/contracts/Migrations.sol
  TDC21/src/migrations/1_initial_migration.js
  TDC21/src/test/.gitkeep
  TDC21/src/truffle-config.js
  docker-compose.yml
Labels: Foundational, subtask

#18 Tdc21 #16 Ownable contract
  .gitignore
  TDC21/src/build/contracts/Migrations.json
  TDC21/src/contracts/Ownable.sol
  TDC21/src/contracts/TDC21.sol
  TDC21/src/interfaces/ERC173.sol
  TDC21/src/migrations/2_ownable_migration.js
  TDC21/src/package-lock.json
  TDC21/src/package.json
  TDC21/src/test/OwnableTest.js
Labels: Foundational, subtask

#21 Tdc21 20 collections contract
  TDC21/src/contracts/Collections.sol
  TDC21/src/migrations/3_contracts_migration.js
  TDC21/src/test/CollectionsTest.js
Labels: Foundational
